### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by anujsphinx** [pointdeveloper/Ionic-send-SMS#1]
i m getting this error on click 
"ReferenceError: sms is not defined"

**Comment by pointdeveloper** [comment]
there must be some problem with the $scope.sms hence you are getting the error..the tutorial works i have double checked.

**Comment by anujsphinx** [comment]
Is anything missing in this code?

**Comment by pointdeveloper** [comment]
It means that the "sms" object was not found the code is fine.
